// Generated by Xata Codegen 0.29.4. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "myproduct",
    columns: [
      { name: "ProductID", type: "int" },
      { name: "Product", type: "string" },
      { name: "Description", type: "text" },
      { name: "Price", type: "float" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Myproduct = InferredTypes["myproduct"];
export type MyproductRecord = Myproduct & XataRecord;

export type DatabaseSchema = {
  myproduct: MyproductRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://Rolando-Vincoy-s-workspace-oc4dtf.us-east-1.xata.sh/db/myDB",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
